### PR TITLE
Rendering module automatically integrating with lmvc's render($args)

### PR DESCRIPTION
**Pull request by tdeekens**
# Templating language integration for lmvc (by a lmvc-module)

This module's intention is to abstract from rendering with various templating languages in an `lmvc` application.
Depending on the application's configuration in its `config.json` it provides a homogenous API from lmvc's controllers.
## Checklist
- [x] Decide upon initially supported templating languages
  - Smarty, Mustache and Json
- [x] Update project's readme [see here](https://github.com/SEP007/lmvc-modules/tree/feature/tmpl-engine-rendering/lib/Scandio/lmvc/modules/rendering)
- [x] Add interfaces and abstract classes
- [x] Document source files
- [x] Implement decided renderers
- [x] Test everything
- [x] Add compatibility trait rerouting old functions
- [x] Add integration branches to [lmvc](https://github.com/SEP007/lmvc/tree/integration/rendering-module) and [lmvc-patat](https://github.com/SEP007/lmvc-patat/tree/integration/rendering-module) and refactor where needed

### CODE REVIEW

**Comment by tdeekens** [comment]
@chriskoch I assume plain old rendering should remain in `lmvc` to not enforce a dependency from `lmvc` to `lmvc-modules`?

**Comment by chriskoch** [comment]
Yes the simple PHP templating should run always. But it should follow the planned new interface anyway.

**Comment by tdeekens** [comment]
Oki dok. Looks pretty cool to be at this point.
- PHP Templating is just treated as everything else
- More responsibilities moved into the rendering module (view finding, etc)
- Added fallback/compatibility trait for controllers adding `renderHtml`..`renderJson`
- After all this is a running version in Patat in respect to the integration branches on the other repos
- Leaves me with testing (yuck)
- and implementing the SmartyHandler, smarty is just weird in my eyes :smile: 

@chriskoch any thoughts, dislikes or wishes?

**Comment by tdeekens** [comment]
@konstantinos-chronis kinda ready for review just missing testing and one handler.

Please dig into the `integration/rendering-module` branch [here](https://github.com/SEP007/lmvc/tree/integration/rendering-module)
and the `integration/rendering-module` branch on Patat [here](https://github.com/SEP007/lmvc-patat/tree/integration/rendering-module)

All three, this one, the lmvc and lmvc-modules branch checked out will give you a running app using with all the changes.

Cheers

**Comment by konstantinos-chronis** [comment]
Good job! Approved!

**Comment by tdeekens** [comment]
Will be merged now as its reviewed and tasks are completed. 
Branch will remain open for further later refinements. More specifics of the implementation remain up for debate.

**Pull request merged**
