### PR TITLE
Implements a logger module following the PSR-3 specification

### PR DESCRIPTION
**Pull request by tdeekens**
# PSR-3 Logger for lmvc-modules

This feature includes a logger following the [PSR-Standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md). It follows interface, class and trait specifications given in the fig-standard.
## Checklist
- [ ] Add and import interface specs
- [ ] Add and import interface trait and abstract class specs
- [ ] Setup logger configuration in LVCConfig
- [ ] Decide upon directory structure for logs
- [ ] Implement storage engine for loggers' logs
- [ ] Add logs-directory to lmvc's `.gitignore`
- [ ] Decide upon integration with [ChomeLogger](http://craig.is/writing/chrome-logger)
## Questions
- Should storage always prepend (on top in editor) or append ('$ tail' works) to log-files
- Should the logger have a config value to automatically keep log files under a certain line limit
- Should the logger automatically split log files by day

Feel free to add comments, wishes or observations in other log libraries. It would be kinda good to get a decent set of the good parts in here and leave the complexity of bad parts out.

### CODE REVIEW

**Comment by tdeekens** [comment]
> @chriskoch wrote:
>  The simplest way is to integrate https://github.com/Seldaek/monolog as a default Logger. But I think it must be configurable through config.json (or composer.json). Because troba is independent to lmvc we have to integrate it twice.

... I feel like it should still remain an lmvc-module though not being hosted in a separate. Then troba would just include lmvc-modules? `config.json` integration is what I'll go for, including levels, log-path etc. 
I think the general consensus for the course is to reuse where possible but not finding the best library and call it a day. So I think I am gonna start small and integrate stuff and ideas which seems reasonable for now instead of writing an adapter for monolog.

**Comment by chriskoch** [comment]
If we put the Logger into a new lmvc-lib project (we need that for string utils too) we do not need to make lmvc-modules mandatory for troba and lmvc.

**Comment by tdeekens** [comment]
True that. So `lmvc-lib` or `lmvc-util` is the name of a new repository and project?
I'll create it in SEP007 if we wanna go with it... and reassign the pull-request of that's possible somehow.

**Comment by tdeekens** [comment]
Pull request moved into new repository `lmvc-utils` [here](https://github.com/SEP007/lmvc-utils/pull/1).

**Pull request closed without merging**
